# Site settings
title: Alessia Lenti
email: alessia.lenti@openmailbox.org
url: https://alessialenti.it
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Illustratrice - Fumettista - Creativa"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 000000
  primary-rgb: "0,0,0"
  secondary: 999999
  secondary-dark: 666666

# Footer settings
footer:
  copyright: Alessia Lenti
  location: Arenzano
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: 
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Credits content
credits: 'blablabla...'

# Build settings
markdown: kramdown
permalink: pretty
