# Site settings
title: Alessia Lenti
email: alessia.lenti@openmailbox.org
url: https://alessialenti.it
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Illustratrice - Fumettista - Creativa"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ffffff
  primary-rgb: "0,0,0"
  secondary: 555555
  secondary-dark: 333333

# Footer settings
footer:
  copyright: Alessia Lenti

# Build settings
markdown: kramdown
permalink: pretty
